services:
  - type: web
    name: rag-qa-api
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        scope: shared
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: HF_EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
        value: python
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: LOG_LEVEL
        value: INFO
    memoryMB: 512
